/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class CompanySearchServices {
    global CompanySearchServices() {

    }
    webService static String CompanySearchService(String jSonText) {
        return null;
    }
    webService static void SaveAccount(String aID, String JsonData) {

    }
    webService static void SaveLead(String lID, String JsonData) {

    }
}
