/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class ContactCapture {
    webService static String CaptureContacts(String captureText, String params) {
        return null;
    }
    webService static String Registered(String thisUid) {
        return null;
    }
    webService static String SaveContacts(String uid, String saveAs, String selectedIds) {
        return null;
    }
    webService static String Validated(String thisUid) {
        return null;
    }
    webService static String makeContact(String lastName) {
        return null;
    }
}
