/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class CreateAccountFromCompanyResultsBatch implements Database.Batchable<BLDS.ResponseResult>, Database.Stateful {
    global CreateAccountFromCompanyResultsBatch(List<BLDS.ResponseResult> resResutls) {

    }
    global void execute(Database.BatchableContext bc, List<BLDS.ResponseResult> data) {

    }
    global void finish(Database.BatchableContext BC) {

    }
    global System.Iterable start(Database.BatchableContext bc) {
        return null;
    }
}
