/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class ProfilerAPI {
    global ProfilerAPI() {

    }
    webService static Boolean WebsitePresent(List<String> accIds) {
        return null;
    }
    webService static String requestCompaniesByAccountIds(List<String> accIds) {
        return null;
    }
    webService static String requestCompaniesByLeadIds(List<String> leadIds) {
        return null;
    }
    webService static String requestCompany(Id accId, String companyURL, Boolean isTest, String testResponse) {
        return null;
    }
    webService static Boolean urlValid(String companyURL) {
        return null;
    }
}
