/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class ResponseResult {
    global String companyName {
        get;
        set;
    }
    global String employees {
        get;
        set;
    }
    global List<String> faxNumbers {
        get;
        set;
    }
    global BLDS.Flags flags {
        get;
        set;
    }
    global Integer foundedYear {
        get;
        set;
    }
    global String id {
        get;
        set;
    }
    global String incorpState {
        get;
        set;
    }
    global Boolean IsChecked {
        get;
        set;
    }
    global BLDS.Location location {
        get;
        set;
    }
    global List<Account> MatchedAccounts {
        get;
        set;
    }
    global String naics {
        get;
        set;
    }
    global String ownership {
        get;
        set;
    }
    global List<String> phoneNumbers {
        get;
        set;
    }
    global String revenue {
        get;
        set;
    }
    global Double score {
        get;
        set;
    }
    global List<String> sics {
        get;
        set;
    }
    global String stockSymbol {
        get;
        set;
    }
    global String tradeName {
        get;
        set;
    }
    global List<String> urls {
        get;
        set;
    }
    global List<String> usSICs {
        get;
        set;
    }
    global ResponseResult() {

    }
}
