/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class SecurityHelper {
    global static Set<String> FIELDS_Account;
    global static Set<String> FIELDS_Attachment;
    global static Set<String> FIELDS_CampaignMember;
    global static Set<String> FIELDS_Contact;
    global static Set<String> FIELDS_Datasuite_License_Keys;
    global static Set<String> FIELDS_Lead;
    global static Set<String> FIELDS_Plan_Report;
    global static Set<String> FIELDS_PlanContactReport;
    global static Set<String> FIELDS_Profiler_Plan;
    global static Set<String> FIELDS_Profiler_Plan_Account;
    global static Set<String> FIELDS_Profiler_Setting;
    global static Set<String> FIELDS_ProfilerResult;
    global static Set<String> FIELDS_Registration;
    global static Set<String> FIELDS_Shield_Field_History;
    global static Set<String> FIELDS_Shield_Setting;
    global static String NO_PERMISSION;
    global static String orgType;
    global SecurityHelper() {

    }
    global static Boolean CheckAccess(Schema.SObjectType obj, Set<String> setFieldNames) {
        return null;
    }
    global static Boolean CheckAccountDelete() {
        return null;
    }
    global static Boolean CheckAccountFieldsSecurity() {
        return null;
    }
    global static Boolean CheckAccountFieldsSecurityInsert() {
        return null;
    }
    global static Boolean CheckAccountFieldsSecurityUpdate() {
        return null;
    }
    global static Boolean CheckAccountInsert() {
        return null;
    }
    global static Boolean CheckAccountUpdate() {
        return null;
    }
    global static Boolean CheckAttachmentCreate() {
        return null;
    }
    global static Boolean CheckAttachmentDelete() {
        return null;
    }
    global static Boolean CheckAttachmentFieldsSecurity() {
        return null;
    }
    global static Boolean CheckAttachmentFieldsSecurityInsert() {
        return null;
    }
    global static Boolean CheckAttachmentFieldsSecurityUpdate() {
        return null;
    }
    global static Boolean CheckAttachmentUpdate() {
        return null;
    }
    global static Boolean CheckCampaignMemberCreate() {
        return null;
    }
    global static Boolean CheckCampaignMemberUpdate() {
        return null;
    }
    global static Boolean CheckContactDelete() {
        return null;
    }
    global static Boolean CheckContactFieldsSecurity() {
        return null;
    }
    global static Boolean CheckContactFieldsSecurityInsert() {
        return null;
    }
    global static Boolean CheckContactFieldsSecurityUpdate() {
        return null;
    }
    global static Boolean CheckContactInsert() {
        return null;
    }
    global static Boolean CheckContactUpdate() {
        return null;
    }
    global static Boolean CheckCreateAble(Schema.SObjectType obj, Set<String> setFieldNames) {
        return null;
    }
    global static Boolean CheckDelete(Schema.SObjectType obj) {
        return null;
    }
    global static Boolean CheckInsert(Schema.SObjectType obj, Set<String> setFieldNames) {
        return null;
    }
    global static Boolean CheckLeadDelete() {
        return null;
    }
    global static Boolean CheckLeadFieldsSecurity() {
        return null;
    }
    global static Boolean CheckLeadFieldsSecurityInsert() {
        return null;
    }
    global static Boolean CheckLeadFieldsSecurityUpdate() {
        return null;
    }
    global static Boolean CheckLeadInsert() {
        return null;
    }
    global static Boolean CheckLeadUpdate() {
        return null;
    }
    global static Boolean CheckPlanContactReportDelete() {
        return null;
    }
    global static Boolean CheckPlanContactReportFieldsSecurity() {
        return null;
    }
    global static Boolean CheckPlanContactReportFieldsSecurityInsert() {
        return null;
    }
    global static Boolean CheckPlanContactReportFieldsSecurityUpdate() {
        return null;
    }
    global static Boolean CheckPlanContactReportInsert() {
        return null;
    }
    global static Boolean CheckPlanContactReportUpdate() {
        return null;
    }
    global static Boolean CheckProfilerPlanAccountDelete() {
        return null;
    }
    global static Boolean CheckProfilerPlanAccountFieldsSecurity() {
        return null;
    }
    global static Boolean CheckProfilerPlanAccountFieldsSecurityInsert() {
        return null;
    }
    global static Boolean CheckProfilerPlanAccountFieldsSecurityUpdate() {
        return null;
    }
    global static Boolean CheckProfilerPlanAccountInsert() {
        return null;
    }
    global static Boolean CheckProfilerPlanAccountUpdate() {
        return null;
    }
    global static Boolean CheckProfilerPlanDelete() {
        return null;
    }
    global static Boolean CheckProfilerPlanFieldsSecurity() {
        return null;
    }
    global static Boolean CheckProfilerPlanFieldsSecurityInsert() {
        return null;
    }
    global static Boolean CheckProfilerPlanFieldsSecurityUpdate() {
        return null;
    }
    global static Boolean CheckProfilerPlanInsert() {
        return null;
    }
    global static Boolean CheckProfilerPlanReportDelete() {
        return null;
    }
    global static Boolean CheckProfilerPlanReportFieldsSecurity() {
        return null;
    }
    global static Boolean CheckProfilerPlanReportFieldsSecurityInsert() {
        return null;
    }
    global static Boolean CheckProfilerPlanReportFieldsSecurityUpdate() {
        return null;
    }
    global static Boolean CheckProfilerPlanReportInsert() {
        return null;
    }
    global static Boolean CheckProfilerPlanReportUpdate() {
        return null;
    }
    global static Boolean CheckProfilerPlanUpdate() {
        return null;
    }
    global static Boolean CheckProfilerResultDelete() {
        return null;
    }
    global static Boolean CheckProfilerResultFieldsSecurity() {
        return null;
    }
    global static Boolean CheckProfilerResultFieldsSecurityInsert() {
        return null;
    }
    global static Boolean CheckProfilerResultFieldsSecurityUpdate() {
        return null;
    }
    global static Boolean CheckProfilerResultInsert() {
        return null;
    }
    global static Boolean CheckProfilerResultUpdate() {
        return null;
    }
    global static Boolean CheckShieldHistoryCreate() {
        return null;
    }
    global static Boolean CheckShieldHistoryDelete() {
        return null;
    }
    global static Boolean CheckShieldHistoryFieldsSecurity() {
        return null;
    }
    global static Boolean CheckShieldHistoryFieldsSecurityInsert() {
        return null;
    }
    global static Boolean CheckShieldHistoryFieldsSecurityUpdate() {
        return null;
    }
    global static Boolean CheckShieldHistoryUpdate() {
        return null;
    }
    global static Boolean CheckUpdate(Schema.SObjectType obj, Set<String> setFieldNames) {
        return null;
    }
    global static Boolean CheckUpsert(Schema.SObjectType obj, Set<String> setFieldNames) {
        return null;
    }
    global static Boolean Checkupdateable(Schema.SObjectType obj, Set<String> setFieldNames) {
        return null;
    }
    global static Boolean checkAccountSecurity() {
        return null;
    }
    global static Boolean checkAttachmentSecurity() {
        return null;
    }
    global static Boolean checkContactSecurity() {
        return null;
    }
    global static Boolean checkLeadSecurity() {
        return null;
    }
    global static Boolean checkPlanContactReportSecurity() {
        return null;
    }
    global static Boolean checkProfilerPlanAccountSecurity() {
        return null;
    }
    global static Boolean checkProfilerPlanReportSecurity() {
        return null;
    }
    global static Boolean checkProfilerPlanSecurity() {
        return null;
    }
    global static Boolean checkProfilerResultSecurity() {
        return null;
    }
    global static Boolean checkShieldHistorySecurity() {
        return null;
    }
    global static Set<String> getIPAccountFields() {
        return null;
    }
    global static Set<String> getIPContactFields() {
        return null;
    }
    global static Set<String> getIPLeadFields() {
        return null;
    }
    global static Set<String> getUnAccessableAccountFields() {
        return null;
    }
    global static Set<String> getUnCreateableAccountFields() {
        return null;
    }
    global static Set<String> getViolentAccountFields(Integer kindOfCheck) {
        return null;
    }
}
