@isTest
public class BalanceoSAPWSPediTest {

    public static testmethod void cobertura(){
        
        new BalanceoSAPWSPedi.ArrayOfDT_SE_InventarioBalanceoPedidos_RespBalanceoProductos();
        new BalanceoSAPWSPedi.ArrayOfInteger();
        new BalanceoSAPWSPedi.BalanceoProductos_element();
        new BalanceoSAPWSPedi.DT_SE_InventarioBalanceoPedidos_Req();
        new BalanceoSAPWSPedi.DT_SE_InventarioBalanceoPedidos_Resp();
    }
}