@isTest
public class InventarioBalanceoPedidos_SF_to_ECCTest {
		
    static testmethod void cover(){
        
        new InventarioBalanceoPedidos_SF_to_ECC.ArrayOfDT_SE_InventarioBalanceoPedidos_RespBalanceoProductos();
        new InventarioBalanceoPedidos_SF_to_ECC.ArrayOfInteger();
        new InventarioBalanceoPedidos_SF_to_ECC.BalanceoProductos_element();
        new InventarioBalanceoPedidos_SF_to_ECC.DT_SE_InventarioBalanceoPedidos_Req();
        new InventarioBalanceoPedidos_SF_to_ECC.DT_SE_InventarioBalanceoPedidos_Resp();
        
    }
}