@isTest
public class WsDevolucionesSAPTest {
    
    static testmethod void cobertura(){
        
        WsDevolucionesSAP.DetalleFactura_element respon = new WsDevolucionesSAP.DetalleFactura_element();
        new WsDevolucionesSAP.DevolucionSAP_element();
        new WsDevolucionesSAP.DevolucionSAPResponse_element();
        new WsDevolucionesSAP.DetalleFacturaResponse_element();
        new WsDevolucionesSAP.DevolucionesSapSoap();
        
        
    }

}